Erivas28 patch 1
erivas28/software-product-sprint pull request #3
Opened 2022-06-01 23:27 UTC by erivas28

outline for portfolio

2022-06-03 18:02 UTC, ChenMeng-SPS22 requested changes
See my pm.

2022-06-03 18:51 UTC, erivas28 commented
I believe I deleted the excessive files. Let me know if you need me to do anything else, thanks :)

2022-06-03 20:10 UTC, ChenMeng-SPS22 commented
> 

I think you should remove the entire node_modules/ which contains all the node.js source code.

2022-06-03 20:27 UTC, erivas28 commented
Just did that Chen, let me know if there is anything else :)

2022-06-05 20:55 UTC, erivas28 commented
I am done for Week 1 now Chen, I think this is good for presenting tomorrow. I will work on Week 2 later tonight. :)

2022-06-05 22:56 UTC, ChenMeng-SPS22 approved these changes

2022-06-05 22:56 UTC, ChenMeng-SPS22 commented on portfolio/src/main/webapp/script.js
> +(function () {
Not sure why you define a function and call it immediately. But if this works it's fine.

2022-06-05 23:32 UTC, merged